WebApp_Cinepolis/WebApp_Cinepolis/Controllers/HorariosController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApp_Cinepolis.Models;

namespace WebApp_Cinepolis.Controllers
{
    public class HorariosController : Controller
    {
        private Database_CinepolisEntities db = new Database_CinepolisEntities();
        

        // GET: Horarios
        public ActionResult Index(bool gen_view, int id)
        {
            if (id < 1)
            {
                return RedirectToAction("DBVacia", "Home");
            }
            var horario = db.Horario.Include(h => h.Pelicula).Include(h => h.Sala);
            ViewBag.VistaGeneral = gen_view;
            ViewBag.IdCine = id;
            if (!gen_view)
            {
                horario = from h in horario where h.CineId == id select h;
                
            }
           
            return View(horario.OrderBy(h => h.CineId).ThenBy(h => h.SalaId).ThenBy(h => h.Fecha).ThenBy(h => h.Hora_inicial).ToList()) ;
        }

        // GET: Horarios para una sala en específico
        public ActionResult IndexHorariosSala(int sala_id, int cine_id)
        {
            var horario = db.Horario.Include(h => h.Pelicula).Include(h => h.Sala);
           
            horario = from h in horario where h.CineId == cine_id && h.SalaId == sala_id select h;
            
            ViewBag.IdSalaView = sala_id;
            ViewBag.IdCineView = cine_id;

            return View(horario.OrderBy(h => h.SalaId).ThenBy(h => h.Fecha).ThenBy(h => h.Hora_inicial).ToList());
        }

        // GET: Horarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Horario horario = db.Horario.Find(id);
            if (horario == null)
            {
                return HttpNotFound();
            }
            return View(horario);
        }

        // GET: Horarios/Create
        public ActionResult Create(int? sala_id, int? cine_id)
        {
            ViewBag.PeliculaId = new SelectList(db.Pelicula, "Id", "Nombre");
            if (cine_id != null)
            {
                ViewBag.CineId = new SelectList(db.Cine, "Id", "Nombre", cine_id);
            }
            else
            {
                ViewBag.CineId = new SelectList(db.Cine, "Id", "Nombre");
            }
            if (sala_id != null)
            {

                ViewBag.SalaId = new SelectList(db.Sala, "Id", "Id", sala_id);
            }
            else
            {
                ViewBag.SalaId = new SelectList(db.Sala, "Id", "Id");
            }
            TempData["sala_id"] = sala_id;
            TempData["cine_id"] = cine_id;
            return View();
        }

        // POST: Horarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Fecha,Hora_inicial,Hora_final,SalaId,CineId,PeliculaId")] Horario horario)
        {
            //Revisión de las horas
            if (checkHoras(horario))
            {
                if (ModelState.IsValid)
                {
                    db.Horario.Add(horario);
                    db.SaveChanges();
                    if (TempData["sala_id"] == null)
                    {
                        return RedirectToAction("Index", new { gen_view = false, id = horario.CineId });
                    }
                    return RedirectToAction("IndexHorariosSala", new { sala_id = TempData["sala_id"] , cine_id = TempData["cine_id"] });
                }
            }

            ViewBag.PeliculaId = new SelectList(db.Pelicula, "Id", "Nombre", horario.PeliculaId);
            ViewBag.SalaId = new SelectList(db.Sala, "Id", "Id", horario.SalaId);
            return View(horario);
        }

        // GET: Horarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Horario horario = db.Horario.Find(id);
           
            if (horario == null)
            {
                return HttpNotFound();
            }
            ViewBag.PeliculaId = new SelectList(db.Pelicula, "Id", "Nombre", horario.PeliculaId);
            ViewBag.SalaId = new SelectList(db.Sala.Where(s => s.CineId == horario.CineId), "Id", "Id", horario.SalaId);
            ViewBag.CineId = new SelectList(db.Cine, "Id", "Nombre", horario.CineId);
            
            return View(horario);
        }

        // POST: Horarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Fecha,Hora_inicial,Hora_final,SalaId,CineId,PeliculaId")] Horario horario)
        {
            //revisión de las horas
            if (checkHoras(horario))
            {
                if (ModelState.IsValid)
                {
                    db.Entry(horario).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index", new { gen_view = false, id = horario.CineId });
                }
            }
            
            ViewBag.PeliculaId = new SelectList(db.Pelicula, "Id", "Nombre", horario.PeliculaId);
            ViewBag.SalaId = new SelectList(db.Sala, "Id", "Id", horario.SalaId);
            ViewBag.CineId = new SelectList(db.Cine, "Id", "Nombre", horario.CineId);
            return View(horario);
        }

        // GET: Horarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Horario horario = db.Horario.Find(id);
            if (horario == null)
            {
                return HttpNotFound();
            }
            return View(horario);
        }

        // POST: Horarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Horario horario = db.Horario.Find(id);
            var cine_id = horario.CineId;
            db.Horario.Remove(horario);
            db.SaveChanges();
            return RedirectToAction("Index", new { gen_view = false, id = cine_id });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // Método para la revisión de las horas de inicio y finalización de un horario, se verifica
        // que la inicial sea menor a la de finalización.
        private bool checkHoras(Horario horario)
        {
            if (TimeSpan.Compare(horario.Hora_inicial, horario.Hora_final) == 1 || TimeSpan.Compare(horario.Hora_inicial, horario.Hora_final) == 0)
            {
                ModelState.AddModelError(nameof(horario.Hora_final), "La hora final debe ser mayor a la inicial.");
                return false;
            }
            return true;
        }

        [HttpPost]
        // Método de actualización de las salas correspondientes al id de entrada del Cine
        public JsonResult ActualizarSalasId(int id)
        {
            var sala = db.Sala.Include(s => s.Cine);
            sala = from s in sala where s.CineId == id select s;
            var selectListItems = new Dictionary<int, int>();

            foreach (var s in sala)
            {
                selectListItems.Add(s.Id, s.Id);
            }
            var json = JsonConvert.SerializeObject(selectListItems);
            return Json(json, JsonRequestBehavior.AllowGet);
        }
    }
}

WebApp_Cinepolis/WebApp_Cinepolis/Controllers/SalasController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApp_Cinepolis.Models;

namespace WebApp_Cinepolis.Controllers
{
    public class SalasController : Controller
    {
        private Database_CinepolisEntities db = new Database_CinepolisEntities();

        // GET: Salas
        public ActionResult Index(bool gen_view, int id)
        {
            if (id < 1)
            {
                return RedirectToAction("DBVacia", "Home");
            }
            var sala = db.Sala.Include(s => s.Cine);
            ViewBag.VistaGeneral = gen_view;
            ViewBag.IdCine = id;
            if (!gen_view)
            {
                sala = from s in sala where s.CineId == id select s;
            }
            return View(sala.OrderBy(s => s.CineId).ThenBy(s => s.Id).ToList());
        }

        // GET: Salas/Details/5
        public ActionResult Details(int? id, int? cine_id)
        {
            if (id == null || cine_id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sala sala = db.Sala.Find(id, cine_id);
            if (sala == null)
            {
                return HttpNotFound();
            }
            return View(sala);
        }

        // GET: Salas/Create
        public ActionResult Create(int cine_id)
        {
            ViewBag.CineId = new SelectList(db.Cine, "Id", "Nombre", cine_id);

            ViewBag.IdSalaPosible = getNuevoIdSala(cine_id);
            return View();
        }

        // POST: Salas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Capacidad,CineId")] Sala sala)
        {
            sala.Id = getNuevoIdSala(sala.CineId);
            if (ModelState.IsValid)
            {
                db.Sala.Add(sala);
                db.SaveChanges();
                return RedirectToAction("Index", new { gen_view = false,id = sala.CineId });
            }

            ViewBag.CineId = new SelectList(db.Cine, "Id", "Nombre", sala.CineId);
            return View(sala);
        }

        // GET: Salas/Edit/5
        public ActionResult Edit(int? id, int? cine_id)
        {
            if (id == null || cine_id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sala sala = db.Sala.Find(id, cine_id);
            if (sala == null)
            {
                return HttpNotFound();
            }
            ViewBag.CineId = new SelectList(db.Cine, "Id", "Nombre", sala.CineId);
            return View(sala);
        }

        // POST: Salas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Capacidad,CineId")] Sala sala)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sala).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { gen_view = false, id = sala.CineId });
            }
            ViewBag.CineId = new SelectList(db.Cine, "Id", "Nombre", sala.CineId);
            return View(sala);
        }

        // GET: Salas/Delete/5
        public ActionResult Delete(int? id, int? cine_id)
        {
            if (id == null || cine_id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sala sala = db.Sala.Find(id, cine_id);
            if (sala == null)
            {
                return HttpNotFound();
            }
            return View(sala);
        }

        // POST: Salas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int? cine_id)
        {
            Sala sala = db.Sala.Find(id, cine_id);
            db.Sala.Remove(sala);
            db.SaveChanges();
            return RedirectToAction("Index", new { gen_view = false, id = cine_id });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        // Método de actualización del id de la sala al crearla respecto al Cine seleccionado
        public JsonResult ObtenerSalaId(int id_cine)
        {
            var json = JsonConvert.SerializeObject(getNuevoIdSala(id_cine));
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        // Método privado de obtención del último id de sala para el cine de entrada
        private int getNuevoIdSala(int id_cine)
        {
            var consulta = db.Sala.Where(s => s.CineId == id_cine);
            var nuevo_id = 1;
            if (consulta.Count() != 0)
            {
                nuevo_id = consulta.Max(s => s.Id) + 1;

            }
            return nuevo_id;
        }
    }
}

WebApp_Cinepolis/WebApp_Cinepolis/Views/Salas/Create.cshtml
@model WebApp_Cinepolis.Models.Sala

@{
    ViewBag.Title = "Agregar";
}

<h2>Agregar nueva sala</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <span class="control-label col-md-2"><strong>Id de sala</strong></span>
            <div class="col-md-10">
                <input id="InputSalaId" class="form-control text-box single-line" disabled="disabled" value="@ViewData["IdSalaPosible"]" />
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Capacidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capacidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2"><strong>Cine asociado</strong></span>
            <div class="col-md-10">
                @Html.DropDownList("CineId", null, htmlAttributes: new { @class = "form-control", @id = "DropdownCineId", @onchange= "actualizarIdSala()" })
                @Html.ValidationMessageFor(model => model.CineId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a onclick="history.back()" href="#">Atrás</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/SalasScript.js")
}

WebApp_Cinepolis/WebApp_Cinepolis/Views/Salas/Delete.cshtml
@model WebApp_Cinepolis.Models.Sala

@{
    ViewBag.Title = "Borrar";
}

<h3>¿Está seguro de que desea borrar la siguiente sala?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Id de sala
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Capacidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cine.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cine.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-default" /> |
            <a onclick="history.back()" href="#">Atrás</a>
        </div>
    }
</div>

WebApp_Cinepolis/WebApp_Cinepolis/Views/Salas/Details.cshtml
@model WebApp_Cinepolis.Models.Sala

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles de la sala</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Id de sala
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capacidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacidad)
        </dd>

        <dt>
            Cine asociado
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cine.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id, cine_id = Model.CineId }) |
    <a onclick="history.back()" href="#">Atrás</a>
</p>

WebApp_Cinepolis/WebApp_Cinepolis/Views/Salas/Edit.cshtml
@model WebApp_Cinepolis.Models.Sala

@{
    ViewBag.Title = "Edición";
}

<h2>Edición de sala</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        <span class="control-label col-md-2"><strong>Id de sala</strong></span>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Capacidad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Capacidad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Capacidad, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.CineId)
    <div class="form-group">
        <span class="control-label col-md-2"><strong>Cine asociado</strong></span>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cine.Nombre, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })

        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    <a onclick="history.back()" href="#">Atrás</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp_Cinepolis/WebApp_Cinepolis/Views/Salas/Index.cshtml
@model IEnumerable<WebApp_Cinepolis.Models.Sala>

@{
    ViewBag.Title = "Agregar";
}

<h2>Lista de Salas</h2>

<p>
    @Html.ActionLink("Agregar una nueva sala", "Create", new { cine_id = (int)ViewData["IdCine"] }, null)
</p>

@if ((bool)ViewData["VistaGeneral"])
{
    @Html.ActionLink("Vista anterior", "Index", new { gen_view = false, id = (int)ViewData["IdCine"] })
}
else
{
    @Html.ActionLink("Vista general", "Index", new { gen_view = true, id = (int)ViewData["IdCine"] })

}


<table class="table">
    <tr>
        <th>
            Id de Sala
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Capacidad)
        </th>
        <th>
            Cine asociado
        </th>
        <th style="width:250px"></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Capacidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cine.Nombre)
            </td>
            <td style="width:250px">

                @Html.ActionLink("Editar", "Edit", new { id = item.Id, cine_id = item.CineId }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.Id, cine_id = item.CineId }) |
                @Html.ActionLink("Borrar", "Delete", new { id = item.Id, cine_id = item.CineId }) |
                @Html.ActionLink("Ver horarios", "IndexHorariosSala", "Horarios", new { sala_id = item.Id, cine_id = item.CineId }, null)


            </td>
        </tr>
    }

</table>

@if (Model.Count() == 0)
{
    <h4>No se encontraron salas para este Cine.</h4>
}
@Html.ActionLink("Atrás", "Index", "Home")