WebApp_Cinepolis/WebApp_Cinepolis/Controllers/CinesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApp_Cinepolis.Models;

namespace WebApp_Cinepolis.Controllers
{
    public class CinesController : Controller
    {
        private Database_CinepolisEntities db = new Database_CinepolisEntities();

        // GET: Cines
        public ActionResult Index()
        {
            return View(db.Cine.ToList());
        }

        // GET: Cines/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cine cine = db.Cine.Find(id);
            if (cine == null)
            {
                return HttpNotFound();
            }
            return View(cine);
        }

        // GET: Cines/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cines/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,Ubicacion")] Cine cine)
        {
            if (ModelState.IsValid)
            {
                db.Cine.Add(cine);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cine);
        }

        // GET: Cines/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cine cine = db.Cine.Find(id);
            if (cine == null)
            {
                return HttpNotFound();
            }
            return View(cine);
        }

        // POST: Cines/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Ubicacion")] Cine cine)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cine).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cine);
        }

        // GET: Cines/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cine cine = db.Cine.Find(id);
            if (cine == null)
            {
                return HttpNotFound();
            }
            return View(cine);
        }

        // POST: Cines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cine cine = db.Cine.Find(id);
            db.Cine.Remove(cine);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApp_Cinepolis/WebApp_Cinepolis/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;

using System.Web;
using System.Web.Mvc;
using WebApp_Cinepolis.Models;


namespace WebApp_Cinepolis.Controllers
{
    public class HomeController : Controller
    {
        private Database_CinepolisEntities db = new Database_CinepolisEntities();
        public ActionResult Index()
        {
            
            return View(db.Cine.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult DBVacia()
        {
            return View();
        }
    }
}

WebApp_Cinepolis/WebApp_Cinepolis/Views/Home/About.cshtml
@{
    ViewBag.Title = "Acerca de";
}
<h2>Acerca de</h2>
<h3>Aplicación web de prueba</h3>

<p>Puede accerder al link del repositorio en GitHub en el siguiente link: <a href="https://github.com/Roypc86/MVC_Cinepolis"> GitHub</a></p>

WebApp_Cinepolis/WebApp_Cinepolis/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contacto";
}
<h2>Información de contacto</h2>

<address>
    Roy Padilla Calderón<br />
</address>

<address>
    <strong>Soporte:</strong>   roypc86@gmail.com<br />
    <strong>GitHub:</strong> <a href="https://github.com/Roypc86/Recopilacion_de_proyectos">GitHub/Roypc86</a>
</address>

WebApp_Cinepolis/WebApp_Cinepolis/Views/Home/DBVacia.cshtml
@{
    ViewBag.Title = "Error";
}
<h2>Error</h2>
<h3>Agrega al menos un Cine al sistema en Administrar Cines en la página principal .</h3>

WebApp_Cinepolis/WebApp_Cinepolis/Views/Home/Index.cshtml
@model IEnumerable<WebApp_Cinepolis.Models.Cine>

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h3>Seleccione el Cine</h3>
    <div class="col-md-9">
        <select name="selector-cine" id="selector-cine">
            @foreach (var item in Model)
            {
                <option value=@item.Id>@item.Nombre</option>

            }

        </select>
    </div>
    <div class="col-md-3">
        <p>
            @Html.ActionLink("Administrar Cines", "Index", "Cines")
        </p>

    </div>

</div>

<div class="row">

    <div class="col-md-3">
        <h2>Películas</h2>

        <p><a class="btn btn-default" onclick="onClickPeliculasButton()">Películas del cine</a></p>
    </div>
    <div class="col-md-3">
        <h2>Combos</h2>

        <p><a class="btn btn-default" onclick="onClickCombosButton()">Combos del cine</a></p>
    </div>
    <div class="col-md-3">
        <h2>Salas</h2>

        <p><a class="btn btn-default" onclick="onClickSalasButton()">Salas del cine</a></p>
    </div>
    <div class="col-md-3">
        <h2>Horarios</h2>

        <p><a class="btn btn-default" onclick="onClickHorariosButton()">Horarios del cine</a></p>
    </div>

</div>
@section Scripts {
    @Scripts.Render("~/Scripts/HomeScript.js")
}